version: '3.8'

services:
  db: # MySQLが起動するコンテナ
    image: mysql:8.0.31
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    platform: linux/amd64
    volumes:
      - mysql_data:/var/lib/mysql # データの永続化
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - '3306:3306'

  back:
    build: back/
    # rm -f tmp/pids/server.pidしとくとrailsのサーバ消し損ねたときに便利
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    env_file:
      - ./back/environments/db.env
    volumes:
      - ./back:/app:cached
    depends_on:
      - db
    # ホストコンピュータのポート：Docker内のポート
    ports:
      - 3000:3000

  front:
    build: front/
    command: yarn run dev
    volumes:
      - ./front:/app:cached
    ports:
      # ホストコンピュータのポート：Docker内のポート
      - 8000:3000
    depends_on:
      - back
volumes:
  public-data:
  tmp-data:
  log-data:
  # db-data:
  mysql_data:
