version: 2.1
jobs:
  test:
    docker:
      - image: 'cimg/ruby:2.7.6'
    steps:
      - checkout
      - run:
          name: echo
          command: echo "Hello, world!!"
workflows:
  test_workflow:
    jobs:
      - test
