# version: 2.1
# orbs:
#   ruby: circleci/ruby@2.0.0
#   node: circleci/node@5.0.3
# commands:
#   setup:
#     steps:
#       - checkout
#       - ruby/install-deps
# jobs:
#   build:
#     docker:
#       - image: 'cimg/ruby:2.7.6'
#     working_directory: ~/back
#     steps:
#       - checkout
#       - restore_cache:
#           keys:
#             - gem-cache-v1-{{ checksum "~/back/Gemfile.lock" }}
#             - gem-cache-v1-
#           working_directory: ~/back

#       # gem install
#       - run:
#           command: gem install bundler
#             bundle config set path 'vendor/bundle'
#             bundle install --jobs=4 --retry=3
#           working_directory: ~/back

#       - save_cache:
#           key: gem-cache-v1-{{ checksum "~/back/Gemfile.lock" }}
#           paths:
#             - ~/back/vendor/bundle
#           working_directory: ~/back
#   test:
#     docker:
#       - image: 'cimg/ruby:2.7.6'
#       - image: 'cimg/mysql:5.7.38'
#         name: db
#         environment:
#           MYSQL_DATEBASE: app_test
#           MYSQL_USER: root
#           MYSQL_PASSWORD: rootpassword

#     environment:
#       BUNDLE_JOBS: '3'
#       BUNDLE_RETRY: '3'
#       APP_DATABASE_HOST: '127.0.0.1'
#       RAILS_ENV: test

#     working_directory: ~/back
#     steps:
#       - checkout
#       - run:
#           name: rails db:migrate
#           command: bundle exec rails db:migrate
#       - run:
#           name: Database setup
#           command: 'bundle exec rails db:schema:load --trace'
#       - run:
#           name: Rspec
#           command: bundle exec rspec
# workflows:
#   build_and_test:
#     jobs:
#       - build
#       - test:
#           requires:
#             - build

version: 2.1
jobs:
  test:
    docker:
      - image: 'cimg/ruby:2.7.6'
    steps:
      - checkout
      - run:
          name: echo
          command: echo "Hello, world!!"
workflows:
  test_workflow:
    jobs:
      - test
