version: 2.1
orbs:
  ruby: circleci/ruby@1.1.2
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.6
    working_directory: ~/havits_app/back
    steps:
      - checkout:
          path: ~/havits_app
      - ruby/install-deps

  test:
    docker:
      - image: circleci/ruby:2.7.6
      - image: circleci/mysql:5
        environment:
          MYSQL_DATEBASE: app_test
          MYSQL_USER: root
          MYSQL_PASSWORD: rootpassword
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      APP_DATABASE_HOST: '127.0.0.1'
      RAILS_ENV: test
    working_directory: ~/havits_app/back
    steps:
      - checkout:
          path: ~/havits_app
      - ruby/install-deps
      - run:
          name: Database setup
          command: bundle exec rails db:migrate
      - run:
          name: test
          command: bundle exec rake test

workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
