version: 2.1
orbs:
  ruby: circleci/ruby@2.0.0
  node: circleci/node@5.0.3
commands:
  setup:
    steps:
      - checkout
      - ruby/install-deps
      - node/install-packages:
          pkg-manager: yarn
          cache-key: 'yarn.lock'
jobs:
  build:
    docker:
      - image: 'cimg/ruby:2.7.6'
    steps:
      - setup
  test:
    docker:
      - image: 'cimg/ruby:2.7.6'
      - image: 'cimg/mysql:5.7.38'
        name: db
        environment:
          MYSQL_DATEBASE: app_test
          MYSQL_USER: root
          MYSQL_PASSWORD: rootpassword
    environment:
      BUNDLE_JOBS: '3'
      BUNDLE_RETRY: '3'
      APP_DATABASE_HOST: '127.0.0.1'
      RAILS_ENV: test
    steps:
      - setup
      - run:
          name: rails db:migrate
          command: bundle exec rails db:migrate
      - run:
          name: Database setup
          command: 'bundle exec rails db:schema:load --trace'
      - run:
          name: Rspec
          command: bundle exec rspec
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
