version: 2.1

# 実行するjob
jobs:
  # buildするjob
  build:
    # machine:
    #   image: circleci/classic:edge
    docker:
      - image: cimg/ruby:2.7.6
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
  # testするjob
  test:
    # machine:
    #   image: circleci/classic:edge
    docker:
      - image: cimg/ruby:3.1.2
    steps:
      - checkout
      - run:
          name: docker-compose up -d
          command: docker-compose up -d
      - run: sleep 30
      - run:
          name: docker-compose run back rails db:create RAILS_ENV=test
          command: docker-compose run back rails db:create RAILS_ENV=test
      - run:
          name: docker-compose run back rails db:migrate RAILS_ENV=test
          command: docker-compose run back rails db:migrate RAILS_ENV=test
      - run:
          name: docker-compose run back bundle exec rspec spec
          command: docker-compose run back bundle exec rspec spec
      - run:
          name: docker-compose down
          command: docker-compose down

# 順番を制御するworkflow
workflows:
  build_and_test_and_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
