version: 2.1
jobs:
  test:
    # docker: CI環境にDockerを利用する場合の設定。
    docker:
      - image: 'cimg/ruby:2.7.6'
    # checkout: CI環境上の working_directory の値の場所にGitリポジトリをコピーする。
    steps:
      - checkout
      - run:
          name: echo
          command: echo "Hello, world!!"
workflows:
  test_workflow:
    jobs:
      - test
